module.exports = {
  status: ['All', 'Ongoing', 'Completed'],
  orderby: [
    { title: 'A-Z', value: 'title' },
    { title: 'Z-A', value: 'titlereverse' },
    { title: 'Update', value: 'update' },
    { title: 'Added', value: 'latest' },
    { title: 'Popular', value: 'popular' }
  ],
  types: ['All', 'Manga', 'Manhwa', 'Manhua', 'Comic'],
  genres: [
    'Action',
    'Adult',
    'Adventure',
    'Comedy',
    'Doujinshi',
    'Drama',
    'Ecchi',
    'Fantasy',
    'Gender Bender',
    'Harem',
    'Historical',
    'Horror',
    'Isekai',
    'Josei',
    'Martial Arts',
    'Mature',
    'Mecha',
    'Mystery',
    'Oneshot',
    'Psychological',
    'Romance',
    'School Life',
    'Sci-fi',
    'Seinen',
    'Shotacon',
    'Shoujo',
    'Shoujo Ai',
    'Shounen',
    'Shounen Ai',
    'Slice of Life',
    'Sports',
    'Supernatural',
    'Tragedy',
    'Yuri'
  ]
}
